/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: ../client.go

// Package mock_tags is a generated GoMock package.
package mock_tags

import (
	context "context"
	reflect "reflect"

	resources "github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-10-01/resources"
	gomock "github.com/golang/mock/gomock"
	azure "sigs.k8s.io/cluster-api-provider-azure/azure"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetAtScope mocks base method.
func (m *MockClient) GetAtScope(arg0 context.Context, arg1 azure.TagsSpecGetter) (resources.TagsResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAtScope", arg0, arg1)
	ret0, _ := ret[0].(resources.TagsResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAtScope indicates an expected call of GetAtScope.
func (mr *MockClientMockRecorder) GetAtScope(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAtScope", reflect.TypeOf((*MockClient)(nil).GetAtScope), arg0, arg1)
}

// UpdateAtScope mocks base method.
func (m *MockClient) UpdateAtScope(arg0 context.Context, arg1 azure.TagsSpecGetter, arg2 resources.TagsPatchResource) (resources.TagsResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAtScope", arg0, arg1, arg2)
	ret0, _ := ret[0].(resources.TagsResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAtScope indicates an expected call of UpdateAtScope.
func (mr *MockClientMockRecorder) UpdateAtScope(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAtScope", reflect.TypeOf((*MockClient)(nil).UpdateAtScope), arg0, arg1, arg2)
}
