apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../base
- machine-deployment.yaml
- ../../azure-cluster-identity

patches:
- path: ../../azure-cluster-identity/azurecluster-identity-ref.yaml
- path: patches/ephemeral.yaml
  target:
    group: infrastructure.cluster.x-k8s.io
    kind: AzureMachineTemplate
    name: .*-md-0
    version: v1beta1
- path: patches/ephemeral.yaml
  target:
    group: infrastructure.cluster.x-k8s.io
    kind: AzureMachineTemplate
    name: .*-control-plane
    version: v1beta1
- path: ../../internal-load-balancer/azure-cluster-cidrs-and-frontend-ips.yaml
- path: ../../internal-load-balancer/kubeadm-config-template-worker-node.yaml

sortOptions:
  order: fifo
