apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../base
- machine-deployment.yaml
- ../../azure-cluster-identity

patches:
- path: patches/kubeadm-controlplane.yaml
- path: ../../azure-cluster-identity/azurecluster-identity-ref.yaml
- path: ../../internal-load-balancer/azure-cluster-cidrs-and-frontend-ips.yaml
- target:
    kind: KubeadmConfigTemplate
  patch: |-
    - op: add
      path: /spec/template/spec/preKubeadmCommands/-
      value: echo '10.0.0.100   ${CLUSTER_NAME}-${APISERVER_LB_DNS_SUFFIX}.${AZURE_LOCATION}.cloudapp.azure.com' >> /etc/hosts

sortOptions:
  order: fifo
